version: '3.9'

services:
  mongo_db:
    container_name: dbmongo
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  nodejs-app:
    build: .
    container_name: nodejsserver
    ports:
      - 3000:3000
    volumes: 
      - .:/usr/src/app  
    environment:
      PORT: 3000
      MONGODB_URI: mongodb+srv://ralfiwardhana789:TDtMxpfwVvzyYq1k@cluster0.xwkcjit.mongodb.net/?retryWrites=true&w=majority
    depends_on:
      - mongo_db

  postgres:
    container_name: dbsql_container
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=ralfiwardhana123
  
  web:
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
     

volumes:
  mongo_db: {}
